package io.tieringkv.command;

import io.tieringkv.pubsub.PubSubBroker;
import io.tieringkv.session.ConnectionContext;

import java.util.List;

/**
 * 命令目录（ADR-0348）：默认命令表驱动声明，冻结 129 项；
 * 每次调用返回新实例（与原 CommandRegistry.build 内联列表等价）。
 * 动态 info/exec/command 与扩展命令（向量/JSON/TS）不在此表。
 */
public final class CommandCatalog {

    private static final PubSubBroker DEFAULT_BROKER =
            ConnectionContext.sharedBroker();

    private CommandCatalog() {
    }

    /** 默认命令表（129 项；注册表 132 = 129 + info + exec + command）。 */
    public static List<Command> defaults() {
        return List.of(

                new PingCommand(),
                new EchoCommand(),
                new SetCommand(),
                new GetCommand(),
                new DelCommand(),
                new ExistsCommand(),
                new IncrCommand(),
                new DecrCommand(),
                new IncrByCommand(),
                new DecrByCommand(),
                new AppendCommand(),
                new StrlenCommand(),
                new GetSetCommand(),
                new SetNxCommand(),
                new SetExCommand("setex", 1000),
                new SetExCommand("psetex", 1),
                new GetDelCommand(),
                new GetRangeCommand(),
                new SetRangeCommand(),
                new TtlCommand("ttl"),
                new TtlCommand("pttl"),
                new ExpireCommand("expire", false, 1000),
                new ExpireCommand("pexpire", false, 1),
                new ExpireCommand("expireat", true, 1000),
                new ExpireCommand("pexpireat", true, 1),
                new PersistCommand(),
                new MgetCommand(),
                new MsetCommand(),
                new MsetNxCommand(),
                new DbsizeCommand(),
                new FlushCommand("flushdb"),
                new FlushCommand("flushall"),
                new ScanCommand(),
                new TypeCommand(),
                new ConfigCommand(),
                new ClientCommand(),
                new HashCommand("hset"),
                new HashCommand("hget"),
                new HashCommand("hdel"),
                new HashCommand("hexists"),
                new HashCommand("hlen"),
                new HashCommand("hkeys"),
                new HashCommand("hvals"),
                new HashCommand("hgetall"),
                new HashCommand("hmget"),
                new HashCommand("hmset"),
                new HashCommand("hincrby"),
                new HashCommand("hsetnx"),
                new ListCommand("lpush"),
                new ListCommand("rpush"),
                new ListCommand("lpop"),
                new ListCommand("rpop"),
                new ListCommand("llen"),
                new ListCommand("lrange"),
                new ListCommand("lindex"),
                new ListCommand("lset"),
                new ListCommand("lrem"),
                new ListCommand("ltrim"),
                new SetFamilyCommand("sadd"),
                new SetFamilyCommand("srem"),
                new SetFamilyCommand("sismember"),
                new SetFamilyCommand("scard"),
                new SetFamilyCommand("smembers"),
                new SetFamilyCommand("spop"),
                new SetFamilyCommand("srandmember"),
                new SetFamilyCommand("sinter"),
                new SetFamilyCommand("sunion"),
                new SetFamilyCommand("sdiff"),
                new SetFamilyCommand("sinterstore"),
                new SetFamilyCommand("sunionstore"),
                new SetFamilyCommand("sdiffstore"),
                new ZSetCommand("zadd"),
                new ZSetCommand("zscore"),
                new ZSetCommand("zrange"),
                new ZSetCommand("zrevrange"),
                new ZSetCommand("zrem"),
                new ZSetCommand("zcard"),
                new ZSetCommand("zincrby"),
                new ZSetCommand("zrangebyscore"),
                new ZSetCommand("zcount"),
                new ZSetCommand("zrank"),
                new ZSetCommand("zrevrank"),
                new HelloCommand(),
                new ObjectCommand(),
                new AclCommand(),
                new ScriptCommand("script"),
                new ScriptCommand("eval"),
                new ScriptCommand("evalsha"),
                new PubSubCommand("publish", DEFAULT_BROKER),
                new PubSubCommand("subscribe", DEFAULT_BROKER),
                new PubSubCommand("unsubscribe", DEFAULT_BROKER),
                new PubSubCommand("psubscribe", DEFAULT_BROKER),
                new PubSubCommand("punsubscribe", DEFAULT_BROKER),
                new MultiCommand(),
                new DiscardCommand(),
                new WatchCommand(),
                new HashCommand("hscan"),
                new ListCommand("linsert"),
                new ListCommand("lmove"),
                new ListCommand("rpoplpush"),
                new ZSetCommand("zrangebylex"),
                new ZSetCommand("zlexcount"),
                new ZSetCommand("zremrangebylex"),
                new StreamCommand("xadd"),
                new StreamCommand("xlen"),
                new StreamCommand("xrange"),
                new StreamCommand("xtrim"),
                new StreamCommand("xread"),
                new StreamCommand("xgroup"),
                new StreamCommand("xreadgroup"),
                new StreamCommand("xack"),
                new StreamCommand("xpending"),
                new StreamCommand("xclaim"),
                new StreamCommand("xautoclaim"),
                new BitCommand("setbit"),
                new BitCommand("getbit"),
                new BitCommand("bitcount"),
                new BitCommand("bitpos"),
                new BitCommand("bitop"),
                new GeoCommand("geoadd"),
                new GeoCommand("geopos"),
                new GeoCommand("geodist"),
                new GeoCommand("geohash"),
                new GeoCommand("geosearch"),
                new GeoCommand("georadius"),
                new GeoCommand("georadiusbymember"),
                new ListCommand("blpop"),
                new ListCommand("brpop"),
                new UnwatchCommand()        );
    }
}
