services:
  node1:
    build: .
    container_name: tiering-node1
    command:
      - --nodeId
      - node1
      - --port
      - "7000"
      - --peers
      - node1@node1:7000,node2@node2:7000,node3@node3:7000
      - --data
      - /data
    volumes:
      - data-node1:/data
    networks:
      - tiering-net

  node2:
    build: .
    container_name: tiering-node2
    command:
      - --nodeId
      - node2
      - --port
      - "7000"
      - --peers
      - node1@node1:7000,node2@node2:7000,node3@node3:7000
      - --data
      - /data
    volumes:
      - data-node2:/data
    networks:
      - tiering-net

  node3:
    build: .
    container_name: tiering-node3
    command:
      - --nodeId
      - node3
      - --port
      - "7000"
      - --peers
      - node1@node1:7000,node2@node2:7000,node3@node3:7000
      - --data
      - /data
    volumes:
      - data-node3:/data
    networks:
      - tiering-net

volumes:
  data-node1:
  data-node2:
  data-node3:

networks:
  tiering-net:
    driver: bridge
